# Generated by Django 4.0.1 on 2022-02-21 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTP', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_alta',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 2, 21, 19, 26, 35, 243611), max_length=100, null=True),
        ),
    ]
